POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 3",
    "details": null,
    "maximumAttendees": 1
}

###
POST http://localhost:3333/events/39b69006-92fd-4a3a-8673-90cfa442763c/attendees
Content-Type: application/json

{
    "name": "Rowena",
    "email": "rowena2@gmail.com"
}

###
GET http://localhost:3333/events/39b69006-92fd-4a3a-8673-90cfa442763c

###
GET http://localhost:3333/attendees/6/badge

###
GET http://localhost:3333/attendees/5/check-in

###
GET http://localhost:3333/events/39b69006-92fd-4a3a-8673-90cfa442763c/attendees