POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo evento 2",
    "details": null,
    "maximumAttendees": 1
}

###
POST http://localhost:3333/events/34c91ad3-4dd0-4117-b3e6-7b37930ce526/attendees
Content-Type: application/json

{
    "name": "Rowena",
    "email": "rowena2@gmail.com"
}

###
GET http://localhost:3333/events/34c91ad3-4dd0-4117-b3e6-7b37930ce526

###
GET http://localhost:3333/attendees/3/badge

###
GET http://localhost:3333/attendees/3/check-in